.PYONY: clean

all:
	$(MAKE) -C ./threadpool_03 
	$(MAKE) -C ./threadpool_11
	$(MAKE) -C ./threadpool_98

clean:
	$(MAKE) clean -C ./threadpool_03 
	$(MAKE) clean -C ./threadpool_11
	$(MAKE) clean -C ./threadpool_98